export const availableServices = [
  {
    id: 'domain-registration',
    category: 'Domains',
    name: 'Premium Domain Registration',
    description: 'Secure premium domains with privacy protection and DNS management.',
    price: 14.99,
    billing: 'yearly',
    configurations: ['.com', '.net', '.org', 'WHOIS Privacy', 'DNS Control'],
    addons: ['Domain Lock', 'Email Forwarding'],
  },
  {
    id: 'shared-hosting',
    category: 'Hosting',
    name: 'Shared Hosting Pro',
    description: 'Optimized hosting for business websites with cPanel and SSL included.',
    price: 12.5,
    billing: 'monthly',
    configurations: ['1 Website', '10 Websites', 'Unlimited Bandwidth'],
    addons: ['Daily Backup', 'Managed Migration'],
  },
  {
    id: 'cloud-hosting',
    category: 'Cloud',
    name: 'Elastic Cloud Hosting',
    description: 'Scale infrastructure on demand with managed backups and monitoring.',
    price: 64.0,
    billing: 'monthly',
    configurations: ['2 vCPU / 4 GB', '4 vCPU / 8 GB', '8 vCPU / 16 GB'],
    addons: ['Managed Firewall', 'Monitoring Suite'],
  },
  {
    id: 'dedicated-server',
    category: 'Dedicated',
    name: 'Dedicated Server X',
    description: 'High-performance bare metal server for mission-critical applications.',
    price: 189.0,
    billing: 'monthly',
    configurations: ['Intel Xeon', '32 GB RAM', '64 GB RAM', '1 TB NVMe'],
    addons: ['Managed Support', 'Advanced Security'],
  },
  {
    id: 'ssl-plus',
    category: 'SSL',
    name: 'SSL Plus Certificate',
    description: 'Enterprise-grade encryption for secure transactions and SEO trust.',
    price: 24.99,
    billing: 'yearly',
    configurations: ['Single Domain', 'Wildcard', 'Extended Validation'],
    addons: ['Priority Validation'],
  },
  {
    id: 'sitelock-basic',
    category: 'SiteLock',
    name: 'SiteLock Basic',
    description: 'Daily malware scanning and vulnerability monitoring for business sites.',
    price: 19.99,
    billing: 'monthly',
    configurations: ['Daily Scan', 'Weekly Scan', 'SMART Patch'],
    addons: ['CDN Acceleration'],
  },
  {
    id: 'codeguard-starter',
    category: 'CodeGuard',
    name: 'CodeGuard Starter',
    description: 'Automated website backup and restore with change monitoring.',
    price: 9.99,
    billing: 'monthly',
    configurations: ['5 GB', '10 GB', '25 GB'],
    addons: ['Advanced Restore Support'],
  },
  {
    id: 'magic-spam-defender',
    category: 'Add-ons',
    name: 'Magic Spam Defender',
    description: 'Intelligent spam filtering for hosted email with quarantine dashboard.',
    price: 6.5,
    billing: 'monthly',
    configurations: ['1 Mailbox', '5 Mailboxes', 'Unlimited Mailboxes'],
    addons: ['Advanced Threat Detection'],
  },
];

export const initialOrders = [
  {
    id: 'WSI-100201',
    serviceName: 'Shared Hosting Pro',
    amount: 12.5,
    paymentMethod: 'Credit Card',
    status: 'Paid',
    date: '2026-03-01T09:00:00.000Z',
  },
  {
    id: 'WSI-100199',
    serviceName: 'SSL Plus Certificate',
    amount: 24.99,
    paymentMethod: 'PayPal',
    status: 'Pending Review',
    date: '2026-02-22T10:30:00.000Z',
  },
];

export const initialMyServices = [
  {
    id: 'svc-1001',
    name: 'Shared Hosting Pro',
    category: 'Hosting',
    status: 'Active',
    renewsOn: '2026-09-14T00:00:00.000Z',
    plan: '10 Websites',
  },
  {
    id: 'svc-1002',
    name: 'SSL Plus Certificate',
    category: 'SSL',
    status: 'Undergoing Provisioning',
    renewsOn: '2027-02-22T00:00:00.000Z',
    plan: 'Wildcard',
  },
  {
    id: 'svc-1003',
    name: 'CodeGuard Starter',
    category: 'CodeGuard',
    status: 'Unpaid',
    renewsOn: '2026-03-18T00:00:00.000Z',
    plan: '10 GB',
  },
];

export const initialNotifications = [
  {
    id: 'notif-1',
    title: 'Provisioning in progress',
    message: 'Your SSL Plus Certificate is being issued and validated.',
    createdAt: '2026-03-09T08:00:00.000Z',
    type: 'info',
  },
  {
    id: 'notif-2',
    title: 'Invoice reminder',
    message: 'CodeGuard Starter has an unpaid balance due in 3 days.',
    createdAt: '2026-03-08T08:00:00.000Z',
    type: 'warning',
  },
];

export const initialClients = [
  {
    id: 'cl-1001',
    name: 'Acme Digital Inc.',
    email: 'admin@acmedigital.com',
    company: 'Acme Digital Inc.',
    services: 4,
    status: 'Active',
  },
  {
    id: 'cl-1002',
    name: 'Northwind Logistics',
    email: 'it@northwindlogistics.com',
    company: 'Northwind Logistics',
    services: 2,
    status: 'Pending',
  },
  {
    id: 'cl-1003',
    name: 'PixelCraft Studio',
    email: 'ops@pixelcraft.io',
    company: 'PixelCraft Studio',
    services: 6,
    status: 'Active',
  },
];
